# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orderbook_service_pb2 as orderbook__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in orderbook_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderBookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeOrderBook = channel.unary_stream(
                '/orderbook.OrderBookService/SubscribeOrderBook',
                request_serializer=orderbook__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=orderbook__service__pb2.OrderBookUpdate.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/orderbook.OrderBookService/PlaceOrder',
                request_serializer=orderbook__service__pb2.Order.SerializeToString,
                response_deserializer=orderbook__service__pb2.OrderResponse.FromString,
                _registered_method=True)


class OrderBookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeOrderBook': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeOrderBook,
                    request_deserializer=orderbook__service__pb2.SubscribeRequest.FromString,
                    response_serializer=orderbook__service__pb2.OrderBookUpdate.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=orderbook__service__pb2.Order.FromString,
                    response_serializer=orderbook__service__pb2.OrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderbook.OrderBookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orderbook.OrderBookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/orderbook.OrderBookService/SubscribeOrderBook',
            orderbook__service__pb2.SubscribeRequest.SerializeToString,
            orderbook__service__pb2.OrderBookUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/PlaceOrder',
            orderbook__service__pb2.Order.SerializeToString,
            orderbook__service__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
