# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orderbook_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'orderbook_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17orderbook_service.proto\x12\torderbook\"\"\n\x10SubscribeRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"\x80\x01\n\x0fOrderBookUpdate\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12#\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x15.orderbook.PriceLevel\x12#\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x15.orderbook.PriceLevel\x12\x13\n\x0bis_snapshot\x18\x04 \x01(\x08\"-\n\nPriceLevel\x12\r\n\x05price\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"f\n\x05Order\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x0c\n\x04side\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\t\x12\x10\n\x08quantity\x18\x06 \x01(\x05\"1\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xa1\x01\n\x10OrderBookService\x12Q\n\x12SubscribeOrderBook\x12\x1b.orderbook.SubscribeRequest\x1a\x1a.orderbook.OrderBookUpdate\"\x00\x30\x01\x12:\n\nPlaceOrder\x12\x10.orderbook.Order\x1a\x18.orderbook.OrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbook_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEREQUEST']._serialized_start=38
  _globals['_SUBSCRIBEREQUEST']._serialized_end=72
  _globals['_ORDERBOOKUPDATE']._serialized_start=75
  _globals['_ORDERBOOKUPDATE']._serialized_end=203
  _globals['_PRICELEVEL']._serialized_start=205
  _globals['_PRICELEVEL']._serialized_end=250
  _globals['_ORDER']._serialized_start=252
  _globals['_ORDER']._serialized_end=354
  _globals['_ORDERRESPONSE']._serialized_start=356
  _globals['_ORDERRESPONSE']._serialized_end=405
  _globals['_ORDERBOOKSERVICE']._serialized_start=408
  _globals['_ORDERBOOKSERVICE']._serialized_end=569
# @@protoc_insertion_point(module_scope)
