name: Test, Benchmark, and Push

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  test-benchmark-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest

    - name: Run single orderbook benchmark
      run: python benchmarks/single_orderbook_performance_benchmark.py

    - name: Run multiple orderbook benchmark
      run: python benchmarks/multiple_orderbook_performance_benchmark.py

    - name: Store benchmark results
      run: |
        mkdir -p benchmarks/previous_benchmark_results/single_orderbook
        mkdir -p benchmarks/previous_benchmark_results/multiple_orderbook
        mv benchmarks/single_orderbook_results.json benchmarks/previous_benchmark_results/single_orderbook/$(date +%Y%m%d_%H%M%S)_results.json
        mv benchmarks/multiple_orderbook_results.json benchmarks/previous_benchmark_results/multiple_orderbook/$(date +%Y%m%d_%H%M%S)_results.json
        mv benchmarks/*.png benchmarks/previous_benchmark_results/

    - name: Push changes
      if: github.ref != 'refs/heads/main' && success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add benchmarks/previous_benchmark_results
        git commit -m "Add benchmark results [skip ci]" || echo "No changes to commit"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmarks/previous_benchmark_results

    - name: Comment PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const singleResults = JSON.parse(fs.readFileSync('benchmarks/previous_benchmark_results/single_orderbook/$(date +%Y%m%d_%H%M%S)_results.json', 'utf8'));
          const multipleResults = JSON.parse(fs.readFileSync('benchmarks/previous_benchmark_results/multiple_orderbook/$(date +%Y%m%d_%H%M%S)_results.json', 'utf8'));
          
          const formatResults = (results) => {
            return Object.entries(results).map(([op, stats]) => 
              `- ${op}: ${stats.mean.toFixed(2)} Î¼s (mean)`
            ).join('\n');
          };
          
          const body = `## Benchmark Results (commit: ${context.sha})

          ### Single Orderbook Performance
          ${formatResults(singleResults)}

          ### Multiple Orderbook Performance
          ${formatResults(multipleResults)}

          [Full benchmark results](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });